### ISSUE TITLE
Unicode issues

### ISSUE THREAD

**Issue by BinyaminPekar** [uenz/SparkleShare#2]
I was trying to check whether your fork fixes [the old Unicode issue](https://github.com/hbons/SparkleShare/issues/1753). But since I could not clone - I could not check it... It would be nice if you could verify it by creating a folder and a file with a UTF-8 names... Thank you!

**Comment by uenz** [comment]
When the mac and linux version can handle unicode then the updated windows version also can, because now the same release of git is used. If the other two can´t, then i have no solution...

**Comment by BinyaminPekar** [comment]
Your fork indeed fixes this issue. Works great! Thank you very much!

**Comment by BinyaminPekar** [comment]
You probably should update your PR message, adding "Fixes  #1753" among other things...
